# Generated by Django 4.2.1 on 2023-06-20 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_data_created',
            field=models.DateField(default=datetime.date.today, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_last_data_change',
            field=models.DateField(default=datetime.date.today, verbose_name='последнее изменение'),
        ),
    ]
